apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kape-vault-backend
  namespace: kape-system
spec:
  provider:
    vault:
      server: "https://vault.example.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "kape-system"
