FROM golang:1.25.10-alpine
WORKDIR /workspace
COPY task-service/go.mod task-service/go.sum ./
RUN go mod download
COPY task-service/ .
RUN go build -o /usr/local/bin/kape-task-service ./cmd/main/...
ENTRYPOINT ["/usr/local/bin/kape-task-service"]
