apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: {{ .Values.namespace }}
data:
  nats.conf: |
    server_name: $SERVER_NAME
    listen: 0.0.0.0:4222
    http: 0.0.0.0:8222

    jetstream {
      store_dir: /data/jetstream
      max_memory_store: 0
    }

    cluster {
      name: kape-nats
      listen: 0.0.0.0:6222
      routes: [
        {{- $ns := .Values.namespace }}
        {{- $replicas := int .Values.nats.replicaCount }}
        {{- range $i := until $replicas }}
        nats://nats-{{ $i }}.nats-headless.{{ $ns }}.svc:6222,
        {{- end }}
      ]
    }
