// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	task "github.com/kape-io/kape/task-service/internal/domain/task"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// BulkUpdateStatus provides a mock function with given fields: ctx, ids, status
func (_m *Repository) BulkUpdateStatus(ctx context.Context, ids []string, status task.TaskStatus) ([]string, error) {
	ret := _m.Called(ctx, ids, status)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpdateStatus")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, task.TaskStatus) ([]string, error)); ok {
		return rf(ctx, ids, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, task.TaskStatus) []string); ok {
		r0 = rf(ctx, ids, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, task.TaskStatus) error); ok {
		r1 = rf(ctx, ids, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, t
func (_m *Repository) Create(ctx context.Context, t *task.Task) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *task.Task) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Repository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *Repository) FindByID(ctx context.Context, id string) (*task.Task, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*task.Task, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *task.Task); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerStats provides a mock function with given fields: ctx, since
func (_m *Repository) HandlerStats(ctx context.Context, since time.Time) ([]task.HandlerStat, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for HandlerStats")
	}

	var r0 []task.HandlerStat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]task.HandlerStat, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []task.HandlerStat); ok {
		r0 = rf(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]task.HandlerStat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Lineage provides a mock function with given fields: ctx, id
func (_m *Repository) Lineage(ctx context.Context, id string) ([]*task.Task, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Lineage")
	}

	var r0 []*task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*task.Task, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*task.Task); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, f
func (_m *Repository) List(ctx context.Context, f task.ListFilter) ([]*task.Task, int, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*task.Task
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, task.ListFilter) ([]*task.Task, int, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, task.ListFilter) []*task.Task); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, task.ListFilter) int); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, task.ListFilter) error); ok {
		r2 = rf(ctx, f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateStatus provides a mock function with given fields: ctx, id, status, fields
func (_m *Repository) UpdateStatus(ctx context.Context, id string, status task.TaskStatus, fields task.UpdateFields) error {
	ret := _m.Called(ctx, id, status, fields)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, task.TaskStatus, task.UpdateFields) error); ok {
		r0 = rf(ctx, id, status, fields)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
