// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	task "github.com/kape-io/kape/task-service/internal/domain/task"
	mock "github.com/stretchr/testify/mock"
)

// Stream is an autogenerated mock type for the Stream type
type Stream struct {
	mock.Mock
}

// Publish provides a mock function with given fields: t
func (_m *Stream) Publish(t *task.Task) {
	_m.Called(t)
}

// Subscribe provides a mock function with no fields
func (_m *Stream) Subscribe() (<-chan *task.Task, func()) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan *task.Task
	var r1 func()
	if rf, ok := ret.Get(0).(func() (<-chan *task.Task, func())); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() <-chan *task.Task); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func() func()); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}

	return r0, r1
}

// NewStream creates a new instance of Stream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStream(t interface {
	mock.TestingT
	Cleanup(func())
}) *Stream {
	mock := &Stream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
