apiVersion: v1
kind: Service
metadata:
  name: mock-webhook-receiver
  namespace: kape-examples
  labels:
    app: mock-webhook-receiver
spec:
  selector:
    app: mock-webhook-receiver
  ports:
    - name: http
      port: 80
      targetPort: 9000
