apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - 01-mock-api/kustomization.yaml
  - 02-load-generator/kustomization.yaml
  - 03-kape/kustomization.yaml
  - 04-mock-webhook/kustomization.yaml
