FROM golang:1.25-alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o kapeproxy-stub ./cmd/kapeproxy-stub

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /build/kapeproxy-stub /kapeproxy-stub
EXPOSE 8080
ENTRYPOINT ["/kapeproxy-stub"]
